from __future__ import annotations

import time
from pathlib import Path


class ResultReader:
    """
    Reads newest clean_ips file generated by CF-Knife.
    """

    def __init__(

        self,

        base_path: Path

    ):

        self.results_path = (

            Path(base_path)

            / "results"

        )

    def latest_file(self):

        files = sorted(

            self.results_path.glob(

                "clean_ips-*.txt"

            ),

            key=lambda f: f.stat().st_mtime,

            reverse=True

        )

        if not files:

            return None

        return files[0]

    def follow(self):

        while True:

            file = self.latest_file()

            if file:

                break

            time.sleep(0.5)

        with open(

            file,

            "r",

            encoding="utf-8",

            errors="ignore"

        ) as f:

            while True:

                line = f.readline()

                if line:

                    yield line

                else:

                    time.sleep(0.2)